[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "symseq"
version = "0.1.0"
description = "Python library for defining, generating, and analyzing symbolic sequences"
readme = "README.md"
authors = [
    { name = "Renato Duarte", email = "rcfduarte@gmail.com" },
    { name = "Barna Zajzon", email = "barna.zajzon@gmail.com" },
]
maintainers = [
    { name = "Renato Duarte", email = "rcfduarte@gmail.com" },
    { name = "Barna Zajzon", email = "barna.zajzon@gmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = { text = "MIT license" }
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "networkx",
    "nltk",
    "joblib",
    "scipy",
    "tqdm",
    "PyYAML",
    "typer",
]

[project.scripts]
symseq = "symseq.cli:main"

[project.optional-dependencies]
analysis = ["pandas"]
fast-metrics = ["antropy>=0.1.9"]
sax = ["saxpy>=2.0.1"]
notebooks = ["ipython>=8.37.0", "ipykernel>=6.29.5"]
viz = ["matplotlib"]
dev = [
    "coverage", # testing
    "mypy",     # linting
    "pytest",   # testing
    "ruff",     # linting
]

[project.urls]

bugs = "https://github.com:symseqbench/symseq/issues"
changelog = "https://github.com:symseqbench/symseq/blob/master/changelog.md"
homepage = "https://github.com:symseqbench/symseq"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.package-data]
"*" = ["*.*"]


# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"


[tool.ruff]
line-length = 120
target-version = "py311"
extend-exclude = ["docs", "notebooks", "_archive", "deprecated"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "UP", "SIM", "RUF"]
ignore = ["B008", "RUF001", "RUF002", "RUF003"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
