# SPDX-License-Identifier: MIT
# Copyright (c) 2025-present, symseq Contributors

"""
artificial_grammar.py

This module contains the ArtificialGrammar class that can be used to generate artificial grammars akin to those
used in psycholinguistic experiments.
"""

from __future__ import annotations

import copy
import logging
import warnings
from collections.abc import Mapping, Sequence
from concurrent.futures import ProcessPoolExecutor, as_completed
from contextlib import nullcontext
from math import ceil, floor
from multiprocessing import cpu_count
from typing import ClassVar

import networkx as nx
import numpy as np

# internal imports
from symseq.core.sequencer import SymbolicSequencer
from symseq.core.state import State
from symseq.generators.ag import utils
from symseq.generators.ag.generator import (
    generate_random_grammar,
    grammar_with_complexity,
)
from symseq.generators.presets import ag as presets
from symseq.generators.registry import register
from symseq.trial import Target, Trial
from symseq.utils.io import get_logger, save_pickle
from symseq.utils.strtools import string_as_symbols
from symseq.utils.validation import (
    validate_boolean,
    validate_integer,
    validate_length_bounds,
    validate_unit_fraction,
)

logger = get_logger(__name__)

_WORKER_CHUNK_SIZE = 512
_UINT64_HIGH = np.iinfo(np.uint64).max


def _worker_count(value: object) -> int:
    """Resolve a requested process count against the available CPUs."""
    available = cpu_count()
    requested = available if value is None else validate_integer(value, "n_proc", minimum=1)
    return min(requested, available)


def _require_pandas():
    """
    Import and return the optional ``pandas`` dependency.

    Returns
    -------
    module
        The imported ``pandas`` module.

    Raises
    ------
    ImportError
        If pandas is not installed.
    """
    try:
        import pandas as pd
    except ImportError as exc:
        raise ImportError(
            "pandas is required for DataFrame display/analysis paths. "
            "Install symseq with the analysis extra: pip install 'symseq[analysis]'."
        ) from exc
    return pd


@register("ArtificialGrammar")
class ArtificialGrammar(SymbolicSequencer):
    """
    Symbolic sequence with transition rules specified by a directed graph, along with corresponding transition
    probabilities. The sequences are generated by traversing the graph. This formalism can be used to define any
    sequence, provided the states and transitions can be specified (each symbol as a state).

    Attributes
    ----------
    intrinsic_target_granularities : dict of str to str
        Intrinsic targets guaranteed by this sequencer and their granularity. ``ArtificialGrammar`` provides
        ``"grammaticality"`` at the ``"per_trial"`` level.

    References
    ----------
    .. [1] Pothos, E. M. (2010). An entropy model for artificial grammar learning. Frontiers in Psychology, 1(June), 16.
    .. [2] Duarte, R., Seriès, P., & Morrison, A. (2014). Self-Organized Artificial Grammar Learning in Spiking Neural
       Networks. In Proceedings of the 36th Annual Conference of the Cognitive Science Society (pp. 427–432).
    .. [3] Bollt, E. M., & Jones, M. a. (2000). The Complexity of Artificial Grammars. Nonlinear Dynamics Psychology and
       Life Sciences, 4(2), 153–168.
    .. [4] Pothos, E. M. (2007). Theories of artificial grammar learning. Psychological Bulletin, 133(2), 227–244.
    """

    intrinsic_target_granularities: ClassVar[dict[str, str]] = {"grammaticality": "per_trial"}

    def __init__(
        self,
        label: str,
        states: list[str],
        alphabet: list[str],
        transitions: list[tuple],  # TODO add option to provide transitions as a matrix, which must then be parsed
        start_states: list[str],
        terminal_states: list[str],
        eos: str = "#",
        rng: np.random.Generator | None = None,
        seed: int = 42,
        validate: bool = True,
        build_graph: bool = True,
        metadata: dict | None = None,
        verbose: bool = False,
        start_probabilities: Mapping[str, float] | None = None,
    ):
        """
        Initialize an ArtificialGrammar from an explicit state set and transition list.

        Parameters
        ----------
        label : str
            Grammar name, used for logging and when saving the grammar to disk.
        states : list of str
            The states of the grammar, i.e., the nodes of the directed graph. Expected format is "SymbolName" or
            "SymbolName(index)", where SymbolName is the name of the symbol and index is the index of the state in
            the FSM. For example, "A(1)", "B (2)" or "C" are all valid state names.

            #For simplicity and robustness of implementation, the nodes should correspond to the individual
            #(unique) symbols that constitute the language
        alphabet : list of str
            The unique symbols that ought to be represented. In many cases, these symbols are different from the
            states, given that the same symbol may correspond to several different nodes, in which case the different
            states for the same symbol are numbered (see examples).
        transitions : list of tuple
            Tuples with the structure (source_state, target_state, transition probability),
            e.g. ``[('a', 'b', 0.1), ('a', 'c', 0.9)]``. Probabilities
            must be finite and non-negative, and outgoing probabilities must sum
            to one for every state with declared transitions. The collection is
            copied before implicit terminal-to-EOS transitions are added.
        start_states : list of str
            The possible start states. See `states` for the format.
        terminal_states : list of str
            The possible terminal states. See `states` for the format.
        eos : str, optional
            Symbol to use as eos (end-of-sequence) marker. Defaults to '#'.
        rng : numpy.random.Generator, optional
            Seeded random number generator. If None, a new default generator is created with seed `seed`.
        seed : int, optional
            Random seed for reproducibility. Ignored if `rng` is not None. Defaults to 42.
        validate : bool, optional
            Whether to validate probabilistic model invariants after structural
            parsing. Structural state and transition checks are always performed.
            Defaults to True.
        build_graph : bool, optional
            Whether to build the networkX graph representation. Defaults to True.
        metadata : dict, optional
            Arbitrary metadata to attach to the grammar, e.g. the complexity measures reported by
            `from_constraints`. Defaults to None.
        verbose : bool, optional
            Whether to log a summary of the grammar. Defaults to False.
        start_probabilities : mapping of str to float, optional
            Sampling probabilities for `start_states`. When omitted, start states remain uniformly distributed.

        Raises
        ------
        ValueError
            If required state sets are empty or inconsistent, transitions are
            malformed, or validation of the probabilistic model fails.
        """
        self.rng = rng if rng is not None else np.random.default_rng(seed)
        self.metadata = metadata

        # consistency checks
        if len(start_states) == 0:
            raise ValueError("No start states provided.")

        if len(terminal_states) == 0:
            raise ValueError("No terminal states provided.")

        # initialize the base class
        super().__init__(
            label=label,
            alphabet_size=len(alphabet),
            alphabet=alphabet,
            rng=np.random.default_rng(self.rng.integers(1, 1000)),
            verbose=verbose,
        )
        self.eos = eos  # end of sequence symbol

        # parse the provided states into proper format and State objects
        self.states, self.start_states, self.terminal_states = self._parse_states(states, start_states, terminal_states)
        self._uniform_start_sampling = start_probabilities is None
        self.start_probabilities = self._parse_start_probabilities(start_probabilities)

        # list (str, not States) and table of all transitions, including the EOS sink
        self.transitions, self.transition_table = self._parse_transitions(transitions)

        if validate:
            self.validate()

        if build_graph:
            self.graph = self.create_graph()

        if verbose:
            ArtificialGrammar.print(self)  # call print method in this class

    @classmethod
    def from_preset(cls, preset_name, seed=42) -> ArtificialGrammar:
        """
        Create an ArtificialGrammar from a preset.

        Parameters
        ----------
        preset_name : str
            Name of the preset to use, as defined in `symseq.generators.presets.ag`.
        seed : int, optional
            Random seed for reproducibility. Defaults to 42.

        Returns
        -------
        ArtificialGrammar
            The ArtificialGrammar object.

        Raises
        ------
        ValueError
            If no preset with the given name exists.
        """
        if preset_name not in presets.__dict__:
            raise ValueError(f"Preset {preset_name} not found.")

        preset = presets.__dict__[preset_name]
        return cls(seed=seed, **preset)

    @classmethod
    def from_sequences(
        cls,
        sequences: Sequence[Sequence[str]],
        *,
        method: str = "markov",
        **kwargs,
    ) -> ArtificialGrammar:
        """
        Infer a regular probabilistic grammar from symbolic sequences.

        Parameters
        ----------
        sequences : sequence of sequence of str
            Corpus of symbolic sequences. Recording boundaries are preserved.
        method : str, optional
            ``"markov"`` for fixed-order/BIC estimation, or ``"vlmc"`` (equivalently ``"context"``) for classical
            context-tree estimation. Defaults to ``"markov"``.
        **kwargs
            Arguments forwarded to the selected inference backend.

        Returns
        -------
        ArtificialGrammar
            The inferred ArtificialGrammar object.

        Raises
        ------
        TypeError
            If called on a subclass of ArtificialGrammar.
        ValueError
            If `method` is not one of ``"markov"``, ``"vlmc"`` or ``"context"``.
        """
        if cls is not ArtificialGrammar:
            raise TypeError("from_sequences currently supports ArtificialGrammar directly.")

        if method == "markov":
            from symseq.generators.ag.inference import infer_markov

            return infer_markov(sequences, **kwargs)
        if method in {"vlmc", "context"}:
            from symseq.generators.ag.inference import infer_vlmc

            return infer_vlmc(sequences, **kwargs)
        raise ValueError("method must be 'markov', 'vlmc', or 'context'.")

    @classmethod
    def from_constraints(
        cls,
        label: str = "Random artificial grammar",
        alphabet_size: int = 4,
        ambiguities: int = 0,
        ambiguity_depth: int = 0,
        n_start_states: int = 1,
        n_terminal_states: int = 1,
        transition_density: float = 0.25,
        assume_equiprobable: bool = True,
        min_string_length: int = 1,
        max_iter: int = int(1e5),
        eos: str = "#",
        rng: np.random.Generator | None = None,
        seed: int = 42,
        verbose: bool = False,
        target_complexity: None | float = None,
        **synthesis_kwargs,
    ) -> ArtificialGrammar:
        """
        Generate an artificial grammar following the specified constraints and properties.
        Formally, each grammatical (valid) string will end with the EOS symbol.

        Parameters
        ----------
        label : str
            Grammar label.
        alphabet_size : int, optional
            Size of the alphabet, i.e., the number of symbols. Defaults to 4.
        ambiguities : int, optional
            How many symbols can be repeated. Defaults to 0.
        ambiguity_depth : int, optional
            Number of different instances (indexed states) of each repeatable symbol. Only relevant if
            ``ambiguities > 0``. Defaults to 0.
        n_start_states : int, optional
            Number of initial states. Defaults to 1.
        n_terminal_states : int, optional
            Number of terminal states corresponding to regular symbols (not EOS), with direct transitions to the
            terminal state (EOS). Defaults to 1.
        transition_density : float, optional
            Density of the transition matrix. Defaults to 0.25.
        assume_equiprobable : bool, optional
            Assume equiprobable outgoing transitions from each state. Defaults to True.
        min_string_length : int, optional
            Minimum length of valid strings in the grammar. Defaults to 1.
        max_iter : int, optional
            Maximum number of attempts to generate a valid grammar. Defaults to 1e5.
        eos : str, optional
            Symbol to use as eos (end-of-sequence) marker. Defaults to '#'.
        rng : numpy.random.Generator, optional
            Seeded random number generator. If None, a new default generator is created with seed `seed`.
        seed : int, optional
            Random seed for reproducibility. Ignored if `rng` is not None. Defaults to 42.
        verbose : bool, optional
            Display progress information. Defaults to False.
        target_complexity : float, optional
            Target transfer-entropy complexity of the grammar. If None, the grammar is drawn randomly under the
            constraints above; otherwise it is synthesized to match this complexity. Defaults to None.
        **synthesis_kwargs
            Additional arguments forwarded to `grammar_with_complexity`. Only used if `target_complexity` is not None.

        Returns
        -------
        ArtificialGrammar
            The ArtificialGrammar object. When `target_complexity` is given, the achieved complexity and related
            synthesis diagnostics are stored in the ``metadata`` attribute.
        """
        if target_complexity is None:
            grammar_pars = generate_random_grammar(
                label=label,
                alphabet_size=alphabet_size,
                ambiguities=ambiguities,
                ambiguity_depth=ambiguity_depth,
                n_start_states=n_start_states,
                n_terminal_states=n_terminal_states,
                transition_density=transition_density,
                assume_equiprobable=assume_equiprobable,
                min_string_length=min_string_length,
                max_iter=max_iter,
                eos=eos,
                rng=rng,
                seed=seed,
                verbose=verbose,
            )
            return cls(rng=rng, seed=seed, verbose=verbose, **grammar_pars)
        else:
            grammar_pars, metadata = grammar_with_complexity(
                label=label,
                alphabet_size=alphabet_size,
                ambiguities=ambiguities,
                ambiguity_depth=ambiguity_depth,
                n_start_states=n_start_states,
                n_terminal_states=n_terminal_states,
                transition_density=transition_density,
                assume_equiprobable=assume_equiprobable,
                min_string_length=min_string_length,
                max_iter=max_iter,
                eos=eos,
                rng=rng,
                seed=seed,
                verbose=verbose,
                target_complexity=target_complexity,
                **synthesis_kwargs,
            )
            return cls(rng=rng, seed=seed, verbose=verbose, metadata=metadata, **grammar_pars)

    # ============================ Grammar construction ============================

    def create_graph(self) -> nx.DiGraph:
        """
        Create a networkX graph object from the grammar.

        Returns
        -------
        nx.DiGraph
            The graph object.
        """
        graph = nx.DiGraph()

        for state in self.states:
            label = str(state)  # symbol + index
            graph.add_node(label, state=state)  # save the state object in the node

        for transition in self.transitions:
            source, target, probability = transition
            graph.add_edge(source, target, weight=probability)

        return graph

    def _parse_transitions(
        self,
        transitions,
    ):
        """
        Parse the provided list of transitions into a list of transition tuples and create the transition table
        (look-up table with all allowed transitions and their probabilities).

        Parameters
        ----------
        transitions : list of tuple
            The transitions of the grammar, as (source_state, destination_state, probability) tuples. The
            source_state and destination_state are strings representing the names of the source and destination
            states, respectively; the probability is the float probability of transitioning from the source state
            to the destination state.

        Returns
        -------
        transitions : list of tuple
            All transitions of the grammar, including the ones added to the EOS sink.
        table : numpy.ndarray
            The transition table, of shape (n_states, n_states), where rows (columns) are targets (sources).

        Notes
        -----
        The caller-owned transition collection is copied. A probability-one EOS
        transition is added to each terminal state that does not declare one.

        Raises
        ------
        ValueError
            If no transitions are supplied, a transition is malformed, or a
            transition references an unknown state.
        """
        supplied_transitions = list(transitions)
        if len(supplied_transitions) == 0:
            raise ValueError("No transitions provided.")

        state_names = {state.tostring() for state in self.states}
        parsed_transitions: list[tuple[str, str, float]] = []
        for index, transition in enumerate(supplied_transitions):
            if not isinstance(transition, (list, tuple)) or len(transition) != 3:
                raise ValueError(f"Transition at index {index} must be a (source, target, probability) triple.")

            source, target, probability = transition
            if not isinstance(source, str) or not isinstance(target, str):
                raise ValueError(f"Transition at index {index} must use string state names.")
            unknown_states = {source, target} - state_names
            if unknown_states:
                raise ValueError(
                    f"Transition at index {index} references an unknown state: {sorted(unknown_states)!r}."
                )
            try:
                parsed_probability = float(probability)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"Transition at index {index} must have a numeric probability.") from exc
            parsed_transitions.append((source, target, parsed_probability))

        declared_edges = {(source, target) for source, target, _ in parsed_transitions}
        for state in self.terminal_states:
            state_name = state.tostring()
            if (state_name, self.eos) not in declared_edges:
                parsed_transitions.append((state_name, self.eos, 1.0))

        table = np.zeros((len(self.states), len(self.states)))
        state_idxs = {state.tostring(): index for index, state in enumerate(self.states)}
        for source, target, probability in parsed_transitions:
            table[state_idxs[target], state_idxs[source]] = probability

        return parsed_transitions, table

    def _parse_states(self, states, start_states, terminal_states):
        """
        Parse the states, start_states and terminal_states arguments into a list of State objects.

        Parameters
        ----------
        states : list of str
            The states of the grammar, i.e., the nodes of the directed graph. Expected format is "SymbolName" or
            "SymbolName(index)", where SymbolName is the name of the symbol and index is the index of the state in
            the FSM. For example, "A(1)", "B (2)" or "C" are all valid state names.

            #For simplicity and robustness of implementation, the nodes should correspond to the individual
            #(unique) symbols that constitute the language
        start_states : list of str
            The possible start symbols.
        terminal_states : list of str
            The possible terminal symbols.

        Returns
        -------
        states_list : list of State
            All states of the grammar, including the EOS state, sorted by symbol name.
        start_states_list : list of State
            The start states, sorted by symbol name.
        terminal_states_list : list of State
            The terminal states, sorted by symbol name.

        Raises
        ------
        ValueError
            If state declarations contain duplicates or invalid references, if EOS
            is declared as a start or terminal state, or if a state's symbol is not
            in the alphabet.
        """
        declarations = {
            "states": list(states),
            "start_states": list(start_states),
            "terminal_states": list(terminal_states),
        }
        for name, values in declarations.items():
            if not all(isinstance(value, str) for value in values):
                raise ValueError(f"{name} must contain only strings.")
            if len(values) != len(set(values)):
                raise ValueError(f"{name} contains duplicate state names.")

        canonical_state_names = [State.from_string(state).tostring() for state in declarations["states"]]
        if len(canonical_state_names) != len(set(canonical_state_names)):
            raise ValueError("states contains duplicate canonical state names.")
        if self.eos in declarations["start_states"] or self.eos in declarations["terminal_states"]:
            raise ValueError("EOS cannot be declared as a start or terminal state.")

        declared_states = set(declarations["states"])
        missing_start_states = set(declarations["start_states"]) - declared_states
        if missing_start_states:
            raise ValueError(f"start_states contains states not present in states: {sorted(missing_start_states)!r}.")
        missing_terminal_states = set(declarations["terminal_states"]) - declared_states
        if missing_terminal_states:
            raise ValueError(
                f"terminal_states contains states not present in states: {sorted(missing_terminal_states)!r}."
            )

        states_list = []
        start_states_list = []
        terminal_states_list = []

        for s in declarations["states"]:
            state = State.from_string(s)  # create a State object

            # check if the symbol name is in the alphabet
            if state.symbol not in self.alphabet and state.symbol != self.eos:
                raise ValueError(f"State {state} with symbol {state.symbol} is not in the alphabet.")

            # add to the list of all, start and terminal states as appropriate
            states_list.append(state)

            if s in declarations["start_states"]:
                start_states_list.append(state)
                state.start = True
            if s in declarations["terminal_states"]:
                terminal_states_list.append(state)
                state.terminal = True

        # add the eos state if it's not already there
        if self.eos not in states_list:
            states_list.append(State.from_string(self.eos))

        # indexed states, unique state in the FSM  - TODO make this clear in the docs
        # sort the lists by symbol name to ensure consistency
        states_list = sorted(states_list, key=lambda s_: s_.symbol)
        start_states_list = sorted(start_states_list, key=lambda s_: s_.symbol)
        terminal_states_list = sorted(terminal_states_list, key=lambda s_: s_.symbol)

        return states_list, start_states_list, terminal_states_list

    def _parse_start_probabilities(
        self,
        probabilities: Mapping[str, float] | None,
    ) -> dict[str, float]:
        """
        Validate the start state sampling probabilities and map them onto the parsed start states.

        Parameters
        ----------
        probabilities : mapping of str to float, optional
            Sampling probability for each start state, keyed by the state's string representation (see
            `State.tostring`). If None, a uniform distribution over the start states is returned.

        Returns
        -------
        dict of str to float
            Sampling probability for each start state, keyed by the state's string representation.

        Raises
        ------
        ValueError
            If the provided keys do not match the start states exactly, if any probability is not finite and
            non-negative, or if the probabilities do not sum to 1.
        """
        start_names = [state.tostring() for state in self.start_states]
        if probabilities is None:
            uniform_probability = 1.0 / len(start_names)
            return {state: uniform_probability for state in start_names}

        if set(probabilities) != set(start_names):
            raise ValueError("start_probabilities must provide exactly one value for every start state.")
        parsed = {state: float(probabilities[state]) for state in start_names}
        if not all(np.isfinite(probability) and probability >= 0.0 for probability in parsed.values()):
            raise ValueError("Start probabilities must be finite and non-negative.")
        if not np.isclose(sum(parsed.values()), 1.0):
            raise ValueError("Start probabilities must sum to 1.")
        return parsed

    def print(self):
        """Log the grammar definition and transition table."""
        logger.info("***************************************************************************")
        if self.label is not None:
            logger.info(f"Generative mechanism: {self.label}")
        logger.info(f"Alphabet: {self.alphabet}")
        logger.info(f"Unique states: {self.states}")
        logger.info(f"Start states: {self.start_states}")
        logger.info(f"Terminal states: {self.terminal_states}")
        logger.info("Transition table (target x source):\n%s", np.array2string(self.transition_table))

    def get_transition_table(self, full=True, correct_terminal_sink=False, verbose=False, binary=False):
        """
        Return a copy of the look-up table with all allowed transitions and their probabilities. If necessary,
        correct for terminal (sink) -> start transitions.

        Parameters
        ----------
        full : bool, optional
            If True, returns the full transition table, including all states and EOS sink. Otherwise, it returns only
            the terminal states without the EOS. Note that in this case the transition probabilities are not corrected
            and the outgoing probabilities for some states may not sum to 1. Defaults to True.
        correct_terminal_sink : bool, optional
            If True, adds a transition from the EOS to all initial states, with the probabilities given by
            `start_probabilities` (uniform by default). Defaults to False.
        verbose : bool, optional
            Display table. Defaults to False.
        binary : bool, optional
            If True, returns the adjacency matrix (1 where a transition is allowed, 0 otherwise) instead of the
            transition probabilities. Defaults to False.

        Returns
        -------
        numpy.ndarray
            The transition table, where the rows (columns) are targets (sources).
        """
        eos_idx = [i for i, s in enumerate(self.states) if s == self.eos]  # index of the EOS, we assume it's present
        table = copy.deepcopy(self.transition_table)

        # add transitions from the terminal states to the initial states with probability 1/n_initial_states
        if correct_terminal_sink:
            for state in self.start_states:
                state_idx = next(i for i, candidate in enumerate(self.states) if candidate == state)
                table[state_idx, eos_idx] = self.start_probabilities[state.tostring()]

        states_as_str = [s.tostring() for s in self.states]
        if not full:
            # remove the EOS from the table (corresponding row and column)
            table = table[
                np.ix_(
                    np.arange(table.shape[0]) != eos_idx,
                    np.arange(table.shape[1]) != eos_idx,
                )
            ]
            logger.warning(
                f"Removed transitions to EOS ({self.eos}) from terminal states. Outgoing probabilities"
                f" from terminal states may not sum to 1 any more."
            )
            states_as_str.remove(self.eos)

        if verbose:
            msg = "Transition table (target x source)"
            if correct_terminal_sink:
                msg += " with corrected terminal probabilities"
            if not full:
                msg += " (EOS sink removed)"

            # select correct set of states and create the table DataFrame for display
            pd = _require_pandas()
            df = pd.DataFrame(table, columns=list(states_as_str), index=list(states_as_str))
            print(df)

            logger.info(msg + ":")
            logger.info("\n" + str(df))

        if binary:
            table = (table > 0.0).astype(int)
        return table

    def get_binary_transition_table(self, full=True, correct_terminal_sink=True, verbose=False) -> np.ndarray:
        """
        Return a copy of the look-up table with all allowed transitions as an adjacency matrix. See also
        `get_transition_table`.

        Parameters
        ----------
        full : bool, optional
            If True, returns the full transition table, including all states and EOS sink. Otherwise, it returns only
            the terminal states without the EOS. Note that in this case the transition probabilities are not corrected
            and the outgoing probabilities for some states may not sum to 1 any more. Defaults to True.
        correct_terminal_sink : bool, optional
            If True, adds a transition from the EOS to all initial states, with the probabilities given by
            `start_probabilities` (uniform by default). Defaults to True.
        verbose : bool, optional
            Display table. Defaults to False.

        Returns
        -------
        numpy.ndarray
            The adjacency matrix, where the rows (columns) are targets (sources).
        """
        transitions = self.get_transition_table(full=full, correct_terminal_sink=correct_terminal_sink, verbose=verbose)
        transitions = transitions > 0.0
        binary_transitions = transitions.astype(int)
        return binary_transitions

    def validate(self):
        """Validate state membership and the probabilistic transition model.

        Returns
        -------
        bool or set of str
            ``True`` if the alphabet is a subset of the unindexed state names;
            otherwise, the alphabet symbols without an identically named state. Indexed
            states may therefore produce a non-empty set even when their symbols are
            represented.

        Raises
        ------
        ValueError
            If state membership is inconsistent, EOS is used as a terminal state,
            transitions are duplicated, probabilities are non-finite or negative, or
            the outgoing probabilities for a state do not sum to one.
        """
        state_names = {state.tostring() for state in self.states}
        start_names = {state.tostring() for state in self.start_states}
        terminal_names = {state.tostring() for state in self.terminal_states}
        if not start_names.issubset(state_names):
            raise ValueError("start_states must be a subset of states.")
        if not terminal_names.issubset(state_names):
            raise ValueError("terminal_states must be a subset of states.")
        if self.eos in terminal_names:
            raise ValueError("EOS cannot be a terminal state.")

        edges: set[tuple[str, str]] = set()
        outgoing_probabilities: dict[str, float] = {}
        for source, target, probability in self.transitions:
            edge = (source, target)
            if edge in edges:
                raise ValueError(f"transitions contains a duplicate edge: {edge!r}.")
            edges.add(edge)
            if source not in state_names or target not in state_names:
                raise ValueError(f"Transition {edge!r} references an unknown state.")
            if not np.isfinite(probability) or probability < 0.0:
                raise ValueError(f"Transition {edge!r} must have a finite, non-negative probability.")
            outgoing_probabilities[source] = outgoing_probabilities.get(source, 0.0) + probability

        for source, total in outgoing_probabilities.items():
            if not np.isclose(total, 1.0, rtol=1e-9, atol=1e-12):
                raise ValueError(f"Outgoing transition probabilities from {source!r} must sum to 1; got {total}.")

        if not set(self.alphabet).issubset(set(self.states)):
            test_var = set(self.alphabet).difference(set(self.states))
            logger.debug(test_var)
            return test_var
        else:
            return True

    def _generate_path(self, source, target, max_length=1000):
        """
        Generate a valid stochastic path from source to target by sampling from the transition table.

        Parameters
        ----------
        source : int
            Index (into `states`) of the start state.
        target : int
            Index (into `states`) of the terminal state.
        max_length : int, optional
            Maximum number of transitions, to avoid infinite loops. Defaults to 1000.

        Returns
        -------
        list of int or None
            State indices forming the path, including source and target. None if a dead end is reached or if no path
            is found within `max_length` transitions.
        """
        path = [source]
        current = source

        for _ in range(max_length):
            if current == target:
                return path

            probs = self.transition_table[:, current]
            if probs.sum() == 0:
                return None  # Dead end

            next_state = self.rng.choice(len(probs), p=probs)
            path.append(next_state)
            current = next_state

        return None  # No path found within limit

    def generate_string(
        self,
        min_length: int = 0,
        max_length: int = int(1e4),
        length_range: tuple[int, int] | list[int] | None = None,
        remove_eos: bool = True,
        as_states: bool = False,
        max_iter: int = int(1e3),
    ) -> list[str]:
        """
        Generate a (grammatical) single string by traversing the grammar. String length is controlled by the arguments
        `min_length`, `max_length`, and `length_range`.

        Parameters
        ----------
        min_length : int, optional
            Minimum string length, including all symbols except the EOS. Defaults to 0.
        max_length : int, optional
            Maximum string length, including all symbols except the EOS. Defaults to 1e4.
        length_range : tuple of int or list of int, optional
            Pair ``(min, max)`` for the length of each string, overriding
            `min_length` and `max_length`. If None, only `min_length` and
            `max_length` are used. Defaults to None.
        remove_eos : bool, optional
            If True, remove eos (e.g., '#') markers from the strings. Defaults to True.
        as_states : bool, optional
            If True, the string will be returned as a list of states (e.g., A, B3) instead of symbols (e.g., A, B).
            Defaults to False.
        max_iter : int, optional
            Maximum attempts (grammar traversals) to generate a valid string. Defaults to 1e3.

        Returns
        -------
        string : list of str
            String as a list of symbols, or of states if `as_states` is True.

        Raises
        ------
        ValueError
            If the effective length bounds are not non-negative integers in
            ascending order, or if `max_iter` is not a positive integer.
        RuntimeError
            If a grammatical string satisfying the length constraints cannot be generated after `max_iter` attempts.
        """
        min_length, max_length = validate_length_bounds(min_length, max_length, length_range)
        max_iter = validate_integer(max_iter, "max_iter", minimum=1)
        remove_eos = validate_boolean(remove_eos, "remove_eos")
        as_states = validate_boolean(as_states, "as_states")

        valid = False
        string = []

        # index of the EOS, we assume it's present
        eos_idx = next(i for i, s in enumerate(self.states) if s == self.eos)
        start_state_idxs = [i for i, s in enumerate(self.states) if s in self.start_states]
        start_probabilities = [self.start_probabilities[self.states[index].tostring()] for index in start_state_idxs]
        # attempt generating a string until a valid one is found
        for _ in range(max_iter):
            if self._uniform_start_sampling:
                start_state_idx = self.rng.choice(start_state_idxs)
            else:
                start_state_idx = self.rng.choice(start_state_idxs, p=start_probabilities)
            path = self._generate_path(start_state_idx, eos_idx, max_length=max_length + 1)  # + 1 for EOS

            if path:
                string = [self.states[i].tostring() for i in path]  # convert table indices to states
                # check string validity by also considering the length constraints
                valid = min_length <= len(string) - 1 <= max_length
                valid = valid and string[-1] == self.eos  # valid if the last symbol is the EOS
                if valid:
                    break

        if not valid:
            raise RuntimeError(
                f"Could not generate a grammatical string that satisfies the constraints after {max_iter} tries."
            )

        # convert to symbols if necessary by removing indices
        if not as_states:
            string = string_as_symbols(string)

        if remove_eos:
            string.remove(self.eos)

        return string

    def _is_symbol_format(self, string: list[str]) -> bool:
        """
        Check if the string contains only symbols (each item is in the alphabet) or also states (indexed).

        Parameters
        ----------
        string : list of str
            The string to check.

        Returns
        -------
        bool
            True if the string is in the symbol format, False otherwise.
        """
        return all(symbol == self.eos or symbol in self.alphabet for symbol in string)

    def add_deviant(
        self,
        string: list[str],
        n_deviants: int = 1,
        max_iter: int = int(1e4),
        remove_eos: bool = True,
        verbose: bool = False,
    ) -> list[str]:
        """
        Make a string non-grammatical by introducing one or more deviants (errors) at random positions.

        Parameters
        ----------
        string : list of str
            The string to make non-grammatical. It can be defined as a list of states (possibly indexed) or a list of
            symbols.
        n_deviants : int, optional
            Number of deviants to introduce. Defaults to 1.
        max_iter : int, optional
            Maximum number of tries to find a valid deviant. Defaults to 1e4.
        remove_eos : bool, optional
            Whether to remove the eos marker from the string. Defaults to True.
        verbose : bool, optional
            Unused, kept for API consistency with the other generation methods. Defaults to False.

        Returns
        -------
        nongramm_string : list of str
            The non-grammatical string specified in the same format (states or symbols) as the input string.

        Raises
        ------
        ValueError
            If the input or generation arguments are invalid, there are too few
            positions, or the grammar contains no alternative emitted symbol.
        RuntimeError
            If no corruption is nongrammatical at both the state and emitted-symbol
            levels within ``max_iter`` attempts.
        """
        del verbose
        if not isinstance(string, Sequence) or isinstance(string, (str, bytes)):
            raise TypeError("string must be a sequence of state or symbol strings.")
        if not all(isinstance(token, str) for token in string):
            raise TypeError("string must contain only strings.")

        n_deviants = validate_integer(n_deviants, "n_deviants", minimum=1)
        max_iter = validate_integer(max_iter, "max_iter", minimum=1)
        remove_eos = validate_boolean(remove_eos, "remove_eos")
        reference = list(string)
        if self.eos in reference[:-1]:
            raise ValueError("EOS may appear only at the end of a string.")
        if not reference or reference[-1] != self.eos:
            reference.append(self.eos)

        positions = list(range(len(reference) - 1))
        if not positions:
            raise ValueError("At least one non-EOS symbol is required to introduce a deviant.")
        if n_deviants > len(positions):
            raise ValueError("n_deviants exceeds the number of non-EOS positions.")

        symbol_input = self._is_symbol_format(reference)
        if symbol_input:
            deviant_elements = sorted(self.alphabet)
        else:
            deviant_elements = sorted(state.tostring() for state in self.states if state != self.eos)
        if len({State.from_string(element).symbol for element in deviant_elements}) < 2:
            raise ValueError("At least two distinct emitted symbols are required to introduce a deviant.")

        for _ in range(max_iter):
            candidate = reference.copy()
            selected = self.rng.choice(positions, size=n_deviants, replace=False)
            for raw_position in np.atleast_1d(selected):
                position = int(raw_position)
                current_symbol = State.from_string(reference[position]).symbol
                alternatives = [
                    element for element in deviant_elements if State.from_string(element).symbol != current_symbol
                ]
                candidate[position] = str(self.rng.choice(alternatives))

            symbols = string_as_symbols(candidate)
            state_grammatical = self.is_grammatical(candidate) if not symbol_input else False
            if not state_grammatical and not self.is_grammatical(symbols):
                if remove_eos:
                    candidate.pop()
                return candidate

        raise RuntimeError(f"Could not make string {list(string)} non-grammatical in {max_iter} tries.")

    def is_grammatical(self, string: Sequence[str | State]) -> bool:
        """Check whether the grammar accepts a complete symbol or state sequence.

        Recognition is state-aware. For symbol input, all currently reachable states
        that emit the next symbol are retained. This is equivalent to traversing a
        nondeterministic finite automaton and preserves distinctions between indexed
        states that emit the same symbol. For explicit state input, every state name
        must follow an exact transition path.

        A sequence is interpreted as symbol input when every non-EOS item belongs to
        ``alphabet``. Otherwise, it is interpreted as explicit state input. This
        preserves the existing convention that indexed names such as ``"B(1)"``
        select particular states, while bare alphabet entries such as ``"B"`` denote
        emitted symbols.

        This method recognizes complete strings rather than prefixes. The EOS marker
        may be omitted and is then appended internally. If supplied, EOS must occur
        exactly once at the end. Empty sequences and sequences containing an internal
        EOS marker are rejected. Transition probabilities affect sampling but not
        structural recognition: every transition declared in ``transitions`` is
        considered an allowed edge.

        Parameters
        ----------
        string : sequence of str or State
            Complete sequence represented as emitted symbols or explicit state names.
            The final EOS marker is optional.

        Returns
        -------
        bool
            ``True`` if at least one valid start-to-EOS state path emits the supplied
            sequence; otherwise ``False``.
        """
        if len(string) == 0:
            return False

        tokens = [item.tostring() if isinstance(item, State) else item for item in string]
        if not all(isinstance(item, str) for item in tokens):
            raise ValueError("Expected every sequence item to be a State or str.")
        if self.eos in tokens[:-1]:
            return False
        if tokens[-1] != self.eos:
            tokens.append(self.eos)

        symbol_input = all(token in self.alphabet for token in tokens[:-1])
        state_symbols = {state.tostring(): state.symbol for state in self.states}
        successors = {state: set() for state in state_symbols}
        for source, target, _ in self.transitions:
            successors[source].add(target)

        def matches(state: str, token: str) -> bool:
            if token == self.eos:
                return state == self.eos
            if symbol_input:
                return state_symbols[state] == token
            return state == token

        reachable = {state.tostring() for state in self.start_states if matches(state.tostring(), tokens[0])}
        for token in tokens[1:]:
            reachable = {target for source in reachable for target in successors[source] if matches(target, token)}
            if not reachable:
                return False

        return self.eos in reachable

    def generate_nongrammatical_string(
        self,
        n_deviants: int = 1,
        min_length: int = 0,
        max_length: int = int(1e4),
        length_range: tuple | None = None,
        remove_eos: bool = True,
        as_states: bool = False,
        max_iter=int(1e4),
    ):
        """
        Convenience function to generate a non-grammatical string.

        For a given string set and a fraction of non-grammatical strings, introduce an appropriate number of deviants
        to create new, non-grammatical strings.

        Parameters
        ----------
        n_deviants : int, optional
            Number of deviants to introduce. Defaults to 1.
        min_length : int, optional
            Minimum string length not including the EOS. Defaults to 0.
        max_length : int, optional
            Maximum string length not including the EOS. Defaults to 1e4.
        length_range : tuple of int, optional
            Tuple of (min, max) for the length of each string, overriding `min_length` and `max_length`. If given,
            both values must be specified. Defaults to None.
        remove_eos : bool, optional
            If True, remove eos (e.g., '#') markers from the strings. Defaults to True.
        as_states : bool, optional
            If True, keep the state indices (e.g., A1) instead of returning bare symbols (e.g., A). Defaults to False.
        max_iter : int, optional
            Maximum attempts to generate a (grammatical or non-grammatical) string. Defaults to 1e4.

        Returns
        -------
        nongramm_string : list of str
            The non-grammatical string.

        Raises
        ------
        RuntimeError
            If a grammatical string satisfying the constraints is not found after `max_iter` attempts, or if it
            cannot be made non-grammatical.
        """
        n_deviants = validate_integer(n_deviants, "n_deviants", minimum=1)
        max_iter = validate_integer(max_iter, "max_iter", minimum=1)
        remove_eos = validate_boolean(remove_eos, "remove_eos")
        as_states = validate_boolean(as_states, "as_states")
        minimum, maximum = validate_length_bounds(min_length, max_length, length_range)
        if n_deviants > maximum:
            raise ValueError("n_deviants cannot exceed the maximum generated string length.")
        minimum = max(minimum, n_deviants)

        string = self.generate_string(
            length_range=(minimum, maximum),
            remove_eos=remove_eos,
            as_states=as_states,
            max_iter=max_iter,
        )

        nongramm_string = self.add_deviant(
            string,
            n_deviants=n_deviants,
            max_iter=max_iter,
            remove_eos=remove_eos,
        )

        if not as_states:
            nongramm_string = string_as_symbols(nongramm_string)

        return nongramm_string

    def _generate_candidate_window(
        self,
        count: int,
        *,
        grammatical: bool,
        generation_kwargs: dict,
        executor: ProcessPoolExecutor | None,
    ) -> list[list[str]]:
        """Generate a deterministic logical window from parent-provided entropy."""
        seeds = self.rng.integers(0, _UINT64_HIGH, size=count, dtype=np.uint64)
        tasks = [
            (
                self,
                grammatical,
                generation_kwargs,
                [int(seed) for seed in seeds[start : start + _WORKER_CHUNK_SIZE]],
            )
            for start in range(0, count, _WORKER_CHUNK_SIZE)
        ]
        map_chunks = map if executor is None else executor.map
        chunks = map_chunks(_generate_string_worker, tasks)
        return [string for chunk in chunks for string in chunk]

    def _collect_candidate_subset(
        self,
        target: int,
        *,
        grammatical: bool,
        replace: bool,
        max_candidates: int,
        uniqueness_by_symbols: bool,
        generation_kwargs: dict,
        executor: ProcessPoolExecutor | None,
    ) -> list[list[str]]:
        """Collect one grammaticality subset with adaptive unique sampling."""
        if target == 0:
            return []
        if replace:
            return self._generate_candidate_window(
                target,
                grammatical=grammatical,
                generation_kwargs=generation_kwargs,
                executor=executor,
            )

        strings: list[list[str]] = []
        seen: set[tuple[str, ...]] = set()
        attempts = 0
        window = target
        while len(strings) < target and attempts < max_candidates:
            window = min(window, max_candidates - attempts)
            candidates = self._generate_candidate_window(
                window,
                grammatical=grammatical,
                generation_kwargs=generation_kwargs,
                executor=executor,
            )
            attempts += len(candidates)
            accepted_before = len(strings)
            for candidate in candidates:
                key_symbols = string_as_symbols(candidate) if uniqueness_by_symbols else candidate
                key = tuple(key_symbols)
                if key in seen:
                    continue
                seen.add(key)
                strings.append(candidate)
                if len(strings) == target:
                    break

            remaining = target - len(strings)
            if remaining == 0:
                break
            acceptance_rate = (len(strings) - accepted_before) / len(candidates)
            estimated = ceil(remaining / acceptance_rate) if acceptance_rate > 0.0 else 4 * remaining
            window = min(max(remaining, estimated), 4 * remaining)

        return strings

    @staticmethod
    def _largest_labeled_batch_size(
        requested: int,
        fraction: float,
        n_grammatical: int,
        n_violations: int,
    ) -> int:
        """Find the largest feasible partial batch preserving floor-rounded labels."""
        low = 0
        high = requested
        while low < high:
            candidate = (low + high + 1) // 2
            required_violations = floor(fraction * candidate)
            required_grammatical = candidate - required_violations
            if required_grammatical <= n_grammatical and required_violations <= n_violations:
                low = candidate
            else:
                high = candidate - 1
        return low

    def _generate_labeled_batch(
        self,
        n_samples: int,
        *,
        min_length: int,
        max_length: int,
        length_range: tuple[int, int] | list[int] | None,
        frac_violations: float,
        n_deviants: int,
        replace: bool,
        strict: bool,
        remove_eos: bool,
        as_states: bool,
        max_iter: int,
        n_proc: int | None,
        max_candidates: int | None,
        uniqueness_by_symbols: bool,
    ) -> tuple[list[list[str]], list[bool]]:
        """Generate a validated, reproducible batch with aligned labels."""
        count = validate_integer(n_samples, "n_samples", minimum=0)
        fraction = validate_unit_fraction(frac_violations, "frac_violations")
        n_deviants = validate_integer(n_deviants, "n_deviants", minimum=1)
        replace = validate_boolean(replace, "replace")
        strict = validate_boolean(strict, "strict")
        remove_eos = validate_boolean(remove_eos, "remove_eos")
        as_states = validate_boolean(as_states, "as_states")
        max_iter = validate_integer(max_iter, "max_iter", minimum=1)
        minimum, maximum = validate_length_bounds(min_length, max_length, length_range)

        workers = _worker_count(n_proc)

        if max_candidates is None:
            candidate_limit = max(10 * count, 1000)
        else:
            candidate_limit = validate_integer(max_candidates, "max_candidates", minimum=1)
            if candidate_limit < count:
                raise ValueError("max_candidates must be at least n_samples.")

        if count == 0:
            return [], []

        n_violations = floor(fraction * count)
        n_grammatical = count - n_violations
        generation_kwargs = {
            "length_range": (minimum, maximum),
            "remove_eos": remove_eos,
            "as_states": as_states,
            "max_iter": max_iter,
        }
        logger.info(
            "Generating %d strings (%d grammatical, %d violations).",
            count,
            n_grammatical,
            n_violations,
        )

        executor_context = nullcontext(None) if workers == 1 else ProcessPoolExecutor(max_workers=workers)
        with executor_context as executor:
            grammatical = self._collect_candidate_subset(
                n_grammatical,
                grammatical=True,
                replace=replace,
                max_candidates=candidate_limit,
                uniqueness_by_symbols=uniqueness_by_symbols,
                generation_kwargs=generation_kwargs,
                executor=executor,
            )
            violation_kwargs = {**generation_kwargs, "n_deviants": n_deviants}
            violations = self._collect_candidate_subset(
                n_violations,
                grammatical=False,
                replace=replace,
                max_candidates=candidate_limit,
                uniqueness_by_symbols=uniqueness_by_symbols,
                generation_kwargs=violation_kwargs,
                executor=executor,
            )

        if replace or (len(grammatical) == n_grammatical and len(violations) == n_violations):
            actual = count
        elif strict:
            raise RuntimeError(
                "Could not generate the requested unique batch within max_candidates: "
                f"{len(grammatical)}/{n_grammatical} grammatical and "
                f"{len(violations)}/{n_violations} violations."
            )
        else:
            actual = self._largest_labeled_batch_size(
                count,
                fraction,
                len(grammatical),
                len(violations),
            )
            actual_violations = floor(fraction * actual)
            actual_grammatical = actual - actual_violations
            grammatical = grammatical[:actual_grammatical]
            violations = violations[:actual_violations]
            message = f"Generated {actual}/{count} unique strings within max_candidates."
            logger.warning(message)
            warnings.warn(message, UserWarning, stacklevel=3)

        combined = [(string, True) for string in grammatical] + [(string, False) for string in violations]
        order = self.rng.permutation(actual)
        strings = [combined[int(index)][0] for index in order]
        labels = [combined[int(index)][1] for index in order]
        return strings, labels

    # ============================ Trial-based API ============================

    def generate_trial(
        self,
        min_length: int = 0,
        max_length: int = int(1e4),
        length_range: tuple | None = None,
        remove_eos: bool = True,
        grammatical: bool = True,
        n_deviants: int = 1,
        max_iter: int = int(1e3),
        **kwargs,
    ) -> Trial:
        """
        Generate one Trial with both symbols and the state-indexed view.

        Parameters
        ----------
        min_length : int, optional
            Minimum string length not including the EOS. Defaults to 0.
        max_length : int, optional
            Maximum string length not including the EOS. Defaults to 1e4.
        length_range : tuple of int, optional
            Tuple of (min, max) for the string length, overriding `min_length` and `max_length`. Defaults to None.
        remove_eos : bool, optional
            If True, remove eos (e.g., '#') markers from the string. Defaults to True.
        grammatical : bool, optional
            If True, draw a grammatical string from the grammar; otherwise corrupt one with `n_deviants` deviants.
            Defaults to True.
        n_deviants : int, optional
            Number of deviants to introduce. Only relevant if `grammatical` is False. Defaults to 1.
        max_iter : int, optional
            Maximum attempts to generate a (grammatical or non-grammatical) string. Defaults to 1e3.
        **kwargs
            Ignored, accepted for API compatibility with the other sequencers.

        Returns
        -------
        Trial
            A single trial, where:

            - ``Trial.symbols``: bare alphabet sequence (e.g. ['A', 'B', 'A']).
            - ``Trial.states``: state-indexed view (e.g. ['A0', 'B1', 'A2']).
            - ``Trial.intrinsic_targets["grammaticality"]``: per-trial bool — True for samples drawn from the
              grammar, False for corrupted samples.
        """
        grammatical = validate_boolean(grammatical, "grammatical")
        if grammatical:
            states = self.generate_string(
                min_length=min_length,
                max_length=max_length,
                length_range=length_range,
                remove_eos=remove_eos,
                as_states=True,
                max_iter=max_iter,
            )
            is_gram = True
        else:
            states = self.generate_nongrammatical_string(
                n_deviants=n_deviants,
                min_length=min_length,
                max_length=max_length,
                length_range=length_range,
                remove_eos=remove_eos,
                as_states=True,
                max_iter=max_iter,
            )
            is_gram = False

        return self._trial_from_states(states, is_gram)

    def _trial_from_states(self, states: list[str], grammatical: bool) -> Trial:
        """Construct a Trial from a state sequence and its grammaticality."""
        symbols = string_as_symbols(states)
        intrinsic_targets = {
            "grammaticality": Target(values=grammatical, mask=None, granularity="per_trial"),
        }
        meta = {
            "paradigm": "ArtificialGrammar",
            "label": self.label,
            "n_states": len(self.states),
            "length": len(symbols),
        }
        return Trial(
            symbols=symbols,
            states=states,
            meta=meta,
            intrinsic_targets=intrinsic_targets,
        )

    def generate_trials(
        self,
        n: int,
        min_length: int = 0,
        max_length: int = int(1e4),
        length_range: tuple[int, int] | list[int] | None = None,
        remove_eos: bool = True,
        frac_violations: float = 0.0,
        n_deviants: int = 1,
        replace: bool = True,
        strict: bool = True,
        max_iter: int = int(1e3),
        n_proc: int | None = 1,
        max_candidates: int | None = None,
    ) -> list[Trial]:
        """
        Generate a labeled batch of artificial-grammar Trials.

        Parameters
        ----------
        n : int
            Number of Trials requested.
        min_length : int, optional
            Minimum sequence length excluding EOS. Defaults to 0.
        max_length : int, optional
            Maximum sequence length excluding EOS. Defaults to 1e4.
        length_range : tuple of int or list of int, optional
            Pair overriding ``min_length`` and ``max_length``. Defaults to None.
        remove_eos : bool, optional
            Whether to remove the terminal EOS marker. Defaults to True.
        frac_violations : float, optional
            Fraction of returned Trials made nongrammatical, rounded down. Defaults to 0.0.
        n_deviants : int, optional
            Number of distinct positions changed in each violation. Defaults to 1.
        replace : bool, optional
            Whether returned symbol sequences may repeat. Defaults to True.
        strict : bool, optional
            Whether an unfilled unique request raises rather than returning a labeled partial batch. Defaults to True.
        max_iter : int, optional
            Per-candidate generation and corruption attempt limit. Defaults to 1e3.
        n_proc : int or None, optional
            Worker-process count. None uses all available CPUs. Defaults to 1.
        max_candidates : int or None, optional
            Per-subset candidate limit for unique sampling. The default is
            ``max(10 * n, 1000)``.

        Returns
        -------
        list of Trial
            Generated Trials with aligned intrinsic grammaticality targets.
        """
        states, labels = self._generate_labeled_batch(
            n,
            min_length=min_length,
            max_length=max_length,
            length_range=length_range,
            frac_violations=frac_violations,
            n_deviants=n_deviants,
            replace=replace,
            strict=strict,
            remove_eos=remove_eos,
            as_states=True,
            max_iter=max_iter,
            n_proc=n_proc,
            max_candidates=max_candidates,
            uniqueness_by_symbols=True,
        )
        return [
            self._trial_from_states(state_sequence, grammatical)
            for state_sequence, grammatical in zip(states, labels, strict=True)
        ]

    def generate_string_set(
        self,
        n_samples: int,
        length_range: tuple[int, int] | list[int] = (1, 1000),
        frac_violations: float = 0.0,
        n_deviants: int = 1,
        replace: bool = True,
        strict: bool = True,
        remove_eos: bool = True,
        as_states: bool = False,
        max_iter: int = int(1e4),
        n_proc: int | None = 1,
        max_candidates: int | None = None,
    ) -> tuple[list[list[str]], list[bool]]:
        """
        Generate a labeled batch of grammatical and violated strings.

        Parameters
        ----------
        n_samples : int
            Number of strings requested.
        length_range : tuple of int or list of int, optional
            Inclusive sequence-length bounds excluding EOS. Defaults to (1, 1000).
        frac_violations : float, optional
            Fraction of returned strings made nongrammatical, rounded down. Defaults to 0.0.
        n_deviants : int, optional
            Number of distinct positions changed in each violation. Defaults to 1.
        replace : bool, optional
            Whether returned strings may repeat. Defaults to True.
        strict : bool, optional
            Whether an unfilled unique request raises rather than returning a labeled partial batch. Defaults to True.
        remove_eos : bool, optional
            Whether to remove the terminal EOS marker. Defaults to True.
        as_states : bool, optional
            Whether to return indexed states rather than bare symbols. Defaults to False.
        max_iter : int, optional
            Per-candidate generation and corruption attempt limit. Defaults to 1e4.
        n_proc : int or None, optional
            Worker-process count. None uses all available CPUs. Defaults to 1.
        max_candidates : int or None, optional
            Per-subset candidate limit for unique sampling. The default is
            ``max(10 * n_samples, 1000)``.

        Returns
        -------
        tuple of list of list of str and list of bool
            Generated strings and aligned grammaticality labels.

        Warns
        -----
        UserWarning
            If ``replace=False`` and ``strict=False`` return a partial batch.

        Raises
        ------
        RuntimeError
            If strict unique sampling cannot fill the requested batch within
            ``max_candidates``.
        """
        return self._generate_labeled_batch(
            n_samples,
            min_length=0,
            max_length=int(1e4),
            length_range=length_range,
            frac_violations=frac_violations,
            n_deviants=n_deviants,
            replace=replace,
            strict=strict,
            remove_eos=remove_eos,
            as_states=as_states,
            max_iter=max_iter,
            n_proc=n_proc,
            max_candidates=max_candidates,
            uniqueness_by_symbols=False,
        )

    def generate_balanced_agl(self, **kwargs):
        """
        Generate a balanced AGL (Artificial Grammar Learning) string set from this grammar.

        Thin wrapper around `symseq.generators.ag.agl_dataset.generate_balanced_agl`.

        Parameters
        ----------
        **kwargs
            Arguments forwarded to `agl_dataset.generate_balanced_agl`, which receives this grammar as its first
            positional argument.

        Returns
        -------
        train_set : list of list of str
            Strings for training.
        test_set : list of pandas.DataFrame
            One DataFrame with test set strings and features per factor cell.
        """
        from symseq.generators.ag import agl_dataset

        return agl_dataset.generate_balanced_agl(self, **kwargs)

    def generate_feature_string_set(
        self,
        n_samples,
        feature_constraints: dict,
        train_set: list[list[str]],
        length_range=(1, 1000),
        # nongramm_fraction=0.0,
        # n_deviants: int = 1,
        # allow_repetitions: bool = True,
        # remove_eos: bool = True,
        # as_states: bool = False,
        # max_iter=int(1e5),
        n_proc=4,
        verbose=False,
    ) -> list[tuple[list[str], dict]]:
        """
        Sample strings whose sequence features fall within the given constraints.

        All strings admitted by the grammar within `length_range` are enumerated exhaustively, their features are
        computed against `train_set`, and `n_samples` strings are drawn at random from those satisfying all
        `feature_constraints`.

        TODO optimized this and remove length constraint

        Parameters
        ----------
        n_samples : int
            Number of strings to sample from the set of valid strings.
        feature_constraints : dict
            Feature constraints, keyed by feature name. Each value is a dict with a ``"value_range"`` entry giving
            the inclusive (min, max) interval the feature must fall into.
        train_set : list of list of str
            Reference corpus against which the (corpus-dependent) features are computed.
        length_range : tuple of int, optional
            String length, specified as the interval (min_len, max_len). The upper bound must not exceed 20, as all
            admissible strings are enumerated exhaustively. Defaults to (1, 1000).
        n_proc : int, optional
            Number of processes to use for parallelization. If None or larger than the number of available CPUs, all
            CPUs are used. Defaults to 4.
        verbose : bool, optional
            Unused, kept for API consistency with the other generation methods. Defaults to False.

        Returns
        -------
        list of tuple
            One (string, feature values) tuple per sampled string, where the string is a list of symbols and the
            feature values are a dict keyed by feature name. Fewer than `n_samples` items are returned (with a
            warning) if not enough strings satisfy the constraints.

        Raises
        ------
        AssertionError
            If the upper bound of `length_range` exceeds 20.
        """
        assert length_range[1] <= 20, "Length range is too large, consider using a smaller range (<20) for now"
        n_proc = min(n_proc or cpu_count(), cpu_count())  # number of processes to use

        start_nodes = [str(s) for s in self.start_states]
        props = {
            "length_range": length_range,
            "eos": self.eos,
        }
        # generate all strings with constrained properties
        string_list = utils.all_paths_as_strings(self.graph, start_nodes, n_proc, **props)
        logging.info(f"Computed {len(string_list)} strings with valid property constraints.")

        str_feature_map = {}
        # compute features for each string, in parallel
        with ProcessPoolExecutor(max_workers=n_proc) as executor:
            futures = [executor.submit(utils.process_feature, s, train_set, feature_constraints) for s in string_list]
            for f in as_completed(futures):
                string, results = f.result()
                str_feature_map[string] = results
        logging.info(f"Computed features for {len(str_feature_map)} strings.")

        # select strings with matching features
        valid_strings = []
        for string, feature_values in str_feature_map.items():
            valid = True
            for k, v in feature_values.items():
                fc = feature_constraints[k]["value_range"]  # feature constraint
                if not (fc[0] <= v <= fc[1]):
                    valid = False
                    break
            if valid:
                valid_strings.append(string)

        # randomly select n_samples strings from the valid strings
        if len(valid_strings) < n_samples:
            logger.warning(
                f"Number of valid strings ({len(valid_strings)}) is less than the required n_samples "
                f"({n_samples})! Returning all valid strings..."
            )
            n_samples = len(valid_strings)

        valid_strings_features = []
        for i in self.rng.choice(len(valid_strings), n_samples, replace=False):
            # tuple of string and feature values (dict)
            valid_strings_features.append((list(valid_strings[i]), str_feature_map[valid_strings[i]]))

        return valid_strings_features

    def save(self, file_name=None, file_path=None):
        """
        Save the current ArtificialGrammar object to a file.

        Parameters
        ----------
        file_name : str, optional
            Name of the file to save. If None, the file name will be generated based on the label. Defaults to None.
        file_path : str, optional
            Path to the directory where the file should be saved. If None, the file will be saved in the current
            working directory. Defaults to None.
        """
        if file_name is None:
            file_name = f"AG_{self.label}.pkl"

        save_pickle(self, file_name, file_path)

    def plot_grammar(self, save=None, **kwargs):
        """
        Plot the grammar as a directed graph.

        Parameters
        ----------
        save : str, optional
            File name to save the plot. If None, the plot will be displayed. Defaults to None.
        **kwargs
            Additional arguments forwarded to `symseq.viz.ag_viz.plot_grammar`.

        Raises
        ------
        ImportError
            If matplotlib is not installed.
        """
        try:
            from symseq.viz.ag_viz import plot_grammar
        except ImportError as exc:
            raise ImportError(
                "matplotlib is required for ArtificialGrammar.plot_grammar. "
                "Install symseq with the viz extra: pip install 'symseq[viz]'."
            ) from exc

        plot_grammar(self, save=save, **kwargs)


def _generate_string_worker(args):
    """
    Generate one deterministic chunk from parent-provided candidate entropy.

    Parameters
    ----------
    args : tuple
        Grammar, grammaticality flag, generation arguments, and ordered candidate
        seeds.

    Returns
    -------
    list of list of str
        The generated strings.

    Notes
    -----
    A shallow grammar copy keeps the sequential fast path from mutating the parent
    RNG. Process workers already receive a pickled copy, but use the same logic so
    results do not depend on the worker count.
    """
    grammar, grammatical, generation_kwargs, seeds = args
    worker_grammar = copy.copy(grammar)
    strings = []
    worker_grammar.rng = np.random.default_rng(np.random.SeedSequence(seeds))
    for _ in seeds:
        if grammatical:
            strings.append(worker_grammar.generate_string(**generation_kwargs))
        else:
            strings.append(worker_grammar.generate_nongrammatical_string(**generation_kwargs))
    return strings
